apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: datadog-secret
    template:
      type: Opaque
  data:
    - secretKey: api-key
      remoteRef:
        key: datadog-api-key # GCP Secret Manager에 저장된 키 이름