datadog:
  apiKeyExistingSecret: "datadog-secret"
  site: "datadoghq.com"
  tags:
    - "env:devops"
    - "module:devops"
  hostname: "custom-hostname"
  apm:
    enabled: true
    portEnabled: true
    hostPortConfig:
      enabled: true
      hostPort: 8126
  logs:
    enabled: true
    containerCollectAll: true

  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false

  containerExclude: "kube_namespace:.*"
  containerInclude: "kube_namespace:namespaceName name:containerName"
  
agents:
  annotations:
    autopilot.gke.io/no-connect: "false"
    
  tolerations:
    - key: "cloud.google.com/compute-class"
      operator: "Equal"
      value: "Scale-Out"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "amd64"
      effect: "NoSchedule"

  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

    processAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

providers:
  gke:
    autopilot: true