apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datadog

helmCharts:
- name: datadog
  repo: https://helm.datadoghq.com
  releaseName: datadog
  valuesFiles:
    - datadog-values.yaml

resources:
- datadog-secret.yaml
